env:
  global:
    - KUBE_VERSION: 1.14
language: go
go:
  - 1.12.1

install:
- export PATH=$GOPATH/bin:$PATH
- mkdir -p $GOPATH/src/k8s.io
- wget https://github.com/kubernetes/kubernetes/archive/v${KUBE_VERSION}.0.tar.gz -P $GOPATH/src/k8s.io
- pushd $GOPATH/src/k8s.io/ && tar xzf v${KUBE_VERSION}.0.tar.gz && mv kubernetes-${KUBE_VERSION}.0 kubernetes && popd
- pushd $GOPATH/src/k8s.io/kubernetes && make generated_files && cp -L -R vendor ${GOPATH}/src/ && rm -r vendor && popd
- go get -v github.com/kubernetes-incubator/reference-docs/gen-compdocs

script:
- make comp
# TODO: uncomment the following to make other docs
# - make api
# - make cli
