env:
  global:
    - KUBE_VERSION: 1.21
    - BUILD_PATH: /home/travis/gopath
language: go
go:
  - 1.16.3

install:
- mkdir -p ${BUILD_PATH}/src/k8s.io
- wget https://github.com/kubernetes/kubernetes/archive/v${KUBE_VERSION}.0.tar.gz -O ${BUILD_PATH}/src/k8s.io/kubernetes-src.tar.gz
- pushd ${BUILD_PATH}/src/k8s.io && tar xzf kubernetes-src.tar.gz && mv kubernetes-${KUBE_VERSION}.0 kubernetes && popd
- pushd ${BUILD_PATH}/src/k8s.io/kubernetes && make generated_files && popd

script:
- make comp
- make genresources
# TODO: uncomment the following to make other docs
# - make api
# - make cli
