env:
  global:
    - KUBE_VERSION: 1.16
language: go
go:
  - 1.12.1

install:
- export PATH=$GOPATH/bin:$PATH
- mkdir -p $GOPATH/src/k8s.io/kubernetes
- wget https://dl.k8s.io/v${KUBE_VERSION}.0/kubernetes-src.tar.gz -P $GOPATH/src/k8s.io/kubernetes
- pushd $GOPATH/src/k8s.io/kubernetes && tar xzf kubernetes-src.tar.gz && popd
- pushd $GOPATH/src/k8s.io/kubernetes && make generated_files && cp -L -R vendor ${GOPATH}/src/ && rm -r vendor && popd
- go get -v github.com/kubernetes-sigs/reference-docs/gen-compdocs

script:
- make comp
# TODO: uncomment the following to make other docs
# - make api
# - make cli
