language: go
go:
  - 1.10.1

install:
- export PATH=$GOPATH/bin:$PATH
- mkdir -p $GOPATH/src/k8s.io
- pushd $GOPATH/src/k8s.io && git clone https://github.com/kubernetes/kubernetes.git && popd

# Checkout the correct version of kubernetes and build generated files, and then
# vendor all packages for resolving dependencies.
- pushd $GOPATH/src/k8s.io/kubernetes && git checkout release-1.10 && make generated_files && cp -L -R vendor $GOPATH/src && rm -r vendor && popd

# Fetch other dependencies if any
- go get -v github.com/kubernetes-incubator/reference-docs/gen-compdocs

# - pushd $GOPATH/src/k8s.io/kubernetes && git checkout release-1.10 && make depended_files && popd
# - cp -L -R $GOPATH/src/k8s.io/kubernetes/vendor/ $GOPATH/src/
#  - rm -r $GOPATH/src/k8s.io/kubernetes/vendor/
# TODO: update API spec

script:
- make comp
# TODO: uncomment the following to make other docs
# - make api
# - make cli
