note: Deployment Config to run 3 nginx instances (max rollback set to 10 revisions).
sample: |
  apiVersion: extensions/v1beta1
  kind: Deployment
  metadata:
    # Unique key of the Deployment instance
    name: deployment-example
  spec:
    # 3 Pods should exist at all times.
    replicas: 3
    # Keep record of 10 revisions for rollback
    revisionHistoryLimit: 10
    template:
      metadata:
        labels:
          # Apply this label to pods and default
          # the Deployment label selector to this value
          app: nginx
      spec:
        containers:
        - name: nginx
          # Run this image
          image: nginx:1.10
